# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yolo_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'yolo_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12yolo_service.proto\x12\x04yolo\"#\n\rDetectRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"f\n\tDetection\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x10\n\x08\x63lass_id\x18\x06 \x01(\x05\"[\n\x0e\x44\x65tectResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12#\n\ndetections\x18\x03 \x03(\x0b\x32\x0f.yolo.Detection2E\n\x0cYoloDetector\x12\x35\n\x06\x44\x65tect\x12\x13.yolo.DetectRequest\x1a\x14.yolo.DetectResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolo_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTREQUEST']._serialized_start=28
  _globals['_DETECTREQUEST']._serialized_end=63
  _globals['_DETECTION']._serialized_start=65
  _globals['_DETECTION']._serialized_end=167
  _globals['_DETECTRESPONSE']._serialized_start=169
  _globals['_DETECTRESPONSE']._serialized_end=260
  _globals['_YOLODETECTOR']._serialized_start=262
  _globals['_YOLODETECTOR']._serialized_end=331
# @@protoc_insertion_point(module_scope)
